# This is a basic workflow that is manually triggered
# https://github.com/actions/starter-workflows/blob/main/automation/manual.yml
# https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow?tool=cli

name: Test Tools

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    # inputs:
    #   name:
    #     # Friendly description to be shown in the UI instead of 'name'
    #     description: 'Person to greet'
    #     # Default value if no value is explicitly provided
    #     default: 'World'
    #     # Input has to be provided for the workflow to run
    #     required: true

jobs:
  build:
    # https://github.blog/changelog/2021-11-16-github-actions-windows-server-2022-with-visual-studio-2022-is-now-generally-available-on-github-hosted-runners/
    runs-on: windows-2022

    steps:
    
    - name: Enable Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1.12.0

    - name: Where cl.exe
      run: cl.exe

    # https://www.gnu.org/software/make/
    - name: Download source
      run: curl -o src.tgz https://ftp.gnu.org/gnu/make/make-4.4.tar.gz
  
    - name: Extract source
      run: tar -xzf src.tgz

    - name: Build source
      working-directory: make-4.4
      run: build_w32.bat

# https://github.com/danielorbach/experiment-windows-actions/actions/workflows/test.yml
# gh workflow run test.yml --ref build
# gh run watch -i 1